spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <GOOGLE_OAUTH_CLIENT_ID>
            client-secret: <GOOGLE_OAUTH_SECRET>
            scope: email,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ofujasldkfjalsf
            client-secret: aldsjflaksdjfkl
          facebook:
            client-id: asldfjlaksfjlkasjfd
            client-secret: asldfjalskdfkjalk
